export declare function cmp_number_asc(a: number, b: number): number;
export declare const cmp_number: typeof cmp_number_asc;
export declare function cmp_number_desc(a: number, b: number): number;
export declare function flatten(a: number[], b: number[]): number[];
export declare function infinities(n: number): number[];
export declare function infinities(n: number, n1: number): number[][];
export declare function infinities(n: number, n1: number, n2: number): number[][][];
export declare function array1d<T>(n: number, v: T): T[];
export declare function check_distance_matrix(mat: number[][], tol: number): boolean | string;
export declare function fix_distance_matrix(mat: number[][], tol: number): number[][];
